import { configureStore } from '@reduxjs/toolkit';
import { setupListeners } from '@reduxjs/toolkit/query';
import { useDispatch, useSelector } from 'react-redux';
import { api } from '../services/api';
import session from '../features/auth/authSlice';
import tasks from '../features/tasks/tasksSlice';
export const store = configureStore({ devTools: false, reducer: { session, tasks, [api.reducerPath]: api.reducer }, middleware: get => get().concat(api.middleware) });
setupListeners(store.dispatch);
export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
export const useAppDispatch = useDispatch.withTypes<AppDispatch>();
export const useAppSelector = useSelector.withTypes<RootState>();
